Microservice update brunch
Denisdeparture/BT3DModelStore pull request #3
Opened 2024-07-15 11:49 UTC by Denisdeparture

2024-07-16 05:23 UTC, dkobzin requested changes

2024-07-16 05:23 UTC, dkobzin commented on Server/Application/Controllers/AccountController.cs
> +                return Redirect(Url.Action("Katalog", "Main")!);
Ошибка скорее всего - надо бы Catalog

2024-07-16 05:23 UTC, dkobzin commented on Server/Application/Controllers/AccountController.cs
>              ExternalLoginInfo? obj = await _signInManager.GetExternalLoginInfoAsync(returnUrl);
Лучше переменный называть не obj а по наимнованию типа с маленькой буквы - camelCase

2024-07-16 05:23 UTC, dkobzin commented on Server/Application/Controllers/AccountController.cs
> +                return Redirect(Url.Action("Katalog", "Main")!);
Ниже то же исправьте

2024-07-16 05:23 UTC, dkobzin commented on Server/Application/HtmlHelpers/FileHtmlTagHelper.cs
> +            if (string.IsNullOrWhiteSpace(pathfromhtmlfile)) return new HtmlString("");
Используйте вместо "" - String.Empty

2024-07-16 05:23 UTC, dkobzin commented on Server/Application/HtmlHelpers/FileHtmlTagHelper.cs
> +                if (string.IsNullOrEmpty(marking)) throw new Exception("marking was null");
Общие строковые переменные лучше вынести в статический класс как константы и использовать их потом везде по имени

2024-07-16 05:23 UTC, dkobzin commented on Server/WebServer/BackgroundServices/RegistrationService.cs
> +            users.CollectionChanged += Users_Register;
Используйте DI / IoC. Часть сервисов,  которые генерируется и обьявлены как  свойства уровне класса  , не должна свойства бытьа обьявлено в конструкторе. Используйте из в методах как локальные на переменные.

2024-07-16 05:23 UTC, dkobzin commented on Server/WebServer/BackgroundServices/RegistrationService.cs
> +            var task = _unitOfWork.adminOperations.CreateRole("Test");
Вынесите строки в отдельный класс типа  Role. Еще лучше как  Enum с приведением к строке

2024-07-16 05:23 UTC, dkobzin commented on Server/WebServer/Controllers/AccountEndpointsController.cs
> +            var user = await _userManager.FindByEmailAsync(obj.Email!);
Необходимо проверять приходящие параметры на  null  с выдачей соотв. исключения. То же сделайте пожалуйста во всех actions

2024-07-16 05:23 UTC, dkobzin commented on Server/WebServer/Controllers/AdminOperationController.cs
> +            _strategy = cond;
Отсутствует проверка входной параметров на nul с выдачей исключения. То же сделайте для всех конструкторов и методов

2024-07-16 05:28 UTC, dkobzin commented
Да и юнит тесты надо не забывать добавлять на вашу функциональности

2024-07-25 06:00 UTC, Denisdeparture commented on Server/Application/Controllers/AccountController.cs
> +                return Redirect(Url.Action("Katalog", "Main")!);
Сделал

2024-07-25 06:00 UTC, Denisdeparture commented on Server/Application/Controllers/AccountController.cs
>              ExternalLoginInfo? obj = await _signInManager.GetExternalLoginInfoAsync(returnUrl);
Исправил

2024-07-25 06:00 UTC, Denisdeparture commented on Server/Application/HtmlHelpers/FileHtmlTagHelper.cs
> +            if (string.IsNullOrWhiteSpace(pathfromhtmlfile)) return new HtmlString("");
Исправил

2024-07-25 06:01 UTC, Denisdeparture commented on Server/Application/HtmlHelpers/FileHtmlTagHelper.cs
> +                if (string.IsNullOrEmpty(marking)) throw new Exception("marking was null");
Сделал папку ConstStorage в бизнес логике

2024-07-25 06:02 UTC, Denisdeparture commented on Server/WebServer/BackgroundServices/RegistrationService.cs
> +            users.CollectionChanged += Users_Register;
Сделал, пришлось отказаться от UnitOfWorkа

2024-07-25 06:02 UTC, Denisdeparture commented on Server/WebServer/BackgroundServices/RegistrationService.cs
> +            var task = _unitOfWork.adminOperations.CreateRole("Test");
Сделал в виде отдельного enum

2024-07-25 06:02 UTC, Denisdeparture commented on Server/WebServer/Controllers/AccountEndpointsController.cs
> +            var user = await _userManager.FindByEmailAsync(obj.Email!);
Сделал

2024-07-25 06:03 UTC, Denisdeparture commented on Server/WebServer/Controllers/AdminOperationController.cs
> +            _strategy = cond;
сделал

2024-08-03 15:00 UTC, merged